lock fix
slimjack/IWC pull request #8
Opened 2017-10-27 09:45 UTC by jasmh

1) fixes updateDataFromStorage so that it updates openWindows before firing the onWindowsChanged event, which triggers clearJunkLocks, which needs to know whether found lock belongs to a closed window and it relies on openWindows for that
2) fixes clearJunkLocks so that it uses interlockedCall with the same id as the lock obtaining code, which gets it in sync with other tabs and solves the problem of removing and obtaining the same lock at the same time in different tabs

2017-10-31 15:23 UTC, slimjack requested changes
One remark. Please, correct. Thank you for contribution.

2017-10-31 15:23 UTC, slimjack commented on src/iwc/Lock.js
> +        return false;
Please, correct the end of function
```
return lockBelongsToClosedWindow || (lockBelongsToThisWindow && (findLock(lockId) === -1));
```

2017-11-01 09:41 UTC, jasmh commented on src/iwc/Lock.js
> +        return false;
Done.

2017-11-01 12:08 UTC, slimjack approved these changes

2017-11-01 12:09 UTC, merged

2017-11-02 09:36 UTC, jasmh commented
Please update the bundled js, I didn't want to do that manually and you don't have the bundle building code included in the source.

2017-11-04 09:15 UTC, slimjack commented
Done